### ISSUE TITLE
Add Dockerfile / docker-compose.yml to containerize web app

### ISSUE THREAD

**Issue by dennislwm** [dennislwm/flask-admin-boilerplate#1]
**Is your feature request related to a problem? Please describe.**
New feature to containerize web app so that user does not need to install python on their pc.

**Describe the solution you'd like**
Dockerfile to build an image, and docker-compose.yml to deploy the build image.

**Describe alternatives you've considered**
see https://github.com/dennislwm/sales_forecast_service/ for example on how to containerize a Python Flask web app

**Comment by mralanlee** [comment]
I can give this a shot

**Comment by dshah2012** [comment]
I can try. I recently did this for my nodejs and mongo db for my company. 
In this case it is the python project right?

**Comment by dennislwm** [comment]
Alright, I'm going to test this by deploying the Dockerfile to Digitalocean Ubuntu server. Windows docker appears to hang for some reason.
